import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const SUPABASE_SECRET_KEY = process.env.SUPABASE_SECRET_KEY!;
const supabase = createClient(SUPABASE_URL, SUPABASE_SECRET_KEY);

interface VideoResourceRow {
  id: number;
  course_id: number;
  section_id: number | null;
  title: string;
  youtube_id: string | null;
  archive_url: string | null;
  video_url: string | null;
  ordering: number;
}

interface CourseSectionRow {
  id: number;
  course_id: number;
  title: string;
}

interface UserVideoProgressRow {
  id: number;
  user_id: string;
  resource_id: number;
  completed: boolean | null;
  completed_at: string | null;
  updated_at: string | null;
}

interface SectionResourceRow {
  section_id: number | null;
  title: string;
  resource_type: string;
  ordering: number;
  archive_url: string | null;
  video_url: string | null;
  pdf_path: string | null;
}

interface CliOptions {
  dryRun: boolean;
}

function parseCliOptions(argv: string[]): CliOptions {
  return {
    dryRun: argv.includes("--dry-run"),
  };
}

function normalizeWhitespace(value: string): string {
  return value.replace(/\s+/g, " ").trim();
}

function toTitleCase(value: string): string {
  return value
    .split(" ")
    .filter(Boolean)
    .map((word) => {
      if (word.length <= 1) return word.toUpperCase();
      if (/^[A-Z0-9]+$/.test(word)) return word;
      return word[0].toUpperCase() + word.slice(1).toLowerCase();
    })
    .join(" ");
}

function isGenericDownloadLabel(value: string): boolean {
  const normalized = normalizeWhitespace(value).toLowerCase();
  if (!normalized) return true;
  if (normalized === "download" || normalized === "file" || normalized === "video") return true;
  if (/^download(\s+(file|video|mp4))?$/.test(normalized)) return true;
  return false;
}

function isAutoGeneratedMediaTitle(value: string): boolean {
  const normalized = normalizeWhitespace(value).toLowerCase();
  if (!normalized) return true;
  if (/^(lecture|recitation|session|episode|track)\s+\d+[a-z]?$/.test(normalized)) {
    return false;
  }
  if (/\b(300k|220k|360p|480p|720p|1080p)\b/.test(normalized)) return true;
  if (/(?:^|[^a-z])(lec|lecture|rec|ses|session|ep|episode|track)[\s._-]*\d/.test(normalized)) {
    if (!/^lecture\s+\d+[:\-]/i.test(value) && !/^recitation\s+\d+[:\-]/i.test(value)) {
      return true;
    }
  }
  return false;
}

function isPreferredHumanTitle(value: string): boolean {
  return !isGenericDownloadLabel(value) && !isAutoGeneratedMediaTitle(value);
}

function normalizeVideoUrl(url: string | null): string | null {
  if (!url) return null;
  const trimmed = url.trim();
  if (!trimmed) return null;

  try {
    const parsed = new URL(trimmed);
    const protocol = "https:";
    const host = parsed.hostname.toLowerCase();
    const pathname = parsed.pathname.replace(/\/+$/, "");
    return `${protocol}//${host}${pathname}`;
  } catch {
    return trimmed.replace(/^http:\/\//i, "https://").replace(/\/+$/, "");
  }
}

function deriveTitleFromMediaUrl(url: string): string | null {
  let filename = "";
  try {
    const parsed = new URL(url);
    filename = decodeURIComponent(parsed.pathname.split("/").pop() ?? "");
  } catch {
    filename = decodeURIComponent(url.split("/").pop() ?? "");
  }

  const stem = filename.replace(/\.[a-z0-9]+$/i, "");
  if (!stem) return null;

  const taggedMatch = (tags: string): RegExpMatchArray | null =>
    stem.match(new RegExp(`(?:^|[^a-z])(?:${tags})[\\s._-]*0*(\\d{1,3})([a-z])?`, "i"));

  const lectureMatch = taggedMatch("lec|lecture|l");
  if (lectureMatch) {
    const suffix = lectureMatch[2] ? lectureMatch[2].toUpperCase() : "";
    return `Lecture ${lectureMatch[1]}${suffix}`;
  }

  const recitationMatch = taggedMatch("rec|recitation");
  if (recitationMatch) {
    const suffix = recitationMatch[2] ? recitationMatch[2].toUpperCase() : "";
    return `Recitation ${recitationMatch[1]}${suffix}`;
  }

  const sessionMatch = taggedMatch("ses|session");
  if (sessionMatch) {
    const suffix = sessionMatch[2] ? sessionMatch[2].toUpperCase() : "";
    return `Session ${sessionMatch[1]}${suffix}`;
  }

  const trackMatch = taggedMatch("track");
  if (trackMatch) {
    const suffix = trackMatch[2] ? trackMatch[2].toUpperCase() : "";
    return `Track ${trackMatch[1]}${suffix}`;
  }

  const episodeMatch = taggedMatch("ep|episode");
  if (episodeMatch) return `Episode ${episodeMatch[1]}`;
  const seasonEpisodeMatch = stem.match(/\bs\d{1,2}e0*(\d{1,3})\b/i);
  if (seasonEpisodeMatch) return `Episode ${seasonEpisodeMatch[1]}`;

  const cleaned = stem
    .replace(/^(mit|ocw)[_-]*/i, "")
    .replace(/\b(300k|220k|360p|480p|720p|1080p)\b/gi, " ")
    .replace(/\btrack\d+(?:_\d+)?\b/gi, " ")
    .replace(/[_-]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();

  if (cleaned) {
    return toTitleCase(cleaned);
  }

  return null;
}

function deriveTitleFromPdfPath(pdfPath: string): string | null {
  if (!pdfPath) return null;

  let pathname = pdfPath;
  try {
    pathname = decodeURIComponent(new URL(pdfPath).pathname);
  } catch {
    pathname = decodeURIComponent(pdfPath.split("?")[0].split("#")[0]);
  }

  const filename = pathname.split("/").pop() ?? "";
  if (!filename) return null;
  const stem = filename.replace(/\.[a-z0-9]+$/i, "");
  if (!stem) return null;

  const cleaned = stem
    .replace(/[_-]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();

  if (!cleaned) return null;
  return toTitleCase(cleaned);
}

function videoKey(row: VideoResourceRow): string {
  if (row.youtube_id) return `yt:${row.youtube_id.toLowerCase()}`;

  const normalizedArchive = normalizeVideoUrl(row.archive_url);
  if (normalizedArchive) return `arch:${normalizedArchive}`;

  const normalizedVideo = normalizeVideoUrl(row.video_url);
  if (normalizedVideo) return `url:${normalizedVideo}`;

  return `title:${normalizeWhitespace(row.title).toLowerCase()}`;
}

function chooseCanonical(rows: VideoResourceRow[]): VideoResourceRow {
  const sorted = [...rows].sort((a, b) => {
    const genericA = isGenericDownloadLabel(a.title);
    const genericB = isGenericDownloadLabel(b.title);
    if (genericA !== genericB) return genericA ? 1 : -1;

    const youtubeA = Boolean(a.youtube_id);
    const youtubeB = Boolean(b.youtube_id);
    if (youtubeA !== youtubeB) return youtubeA ? -1 : 1;

    const archiveA = Boolean(a.archive_url);
    const archiveB = Boolean(b.archive_url);
    if (archiveA !== archiveB) return archiveA ? -1 : 1;

    const videoA = Boolean(a.video_url);
    const videoB = Boolean(b.video_url);
    if (videoA !== videoB) return videoA ? -1 : 1;

    if (a.ordering !== b.ordering) return a.ordering - b.ordering;
    return a.id - b.id;
  });

  return sorted[0];
}

function chunk<T>(items: T[], size: number): T[][] {
  const out: T[][] = [];
  for (let i = 0; i < items.length; i += size) {
    out.push(items.slice(i, i + size));
  }
  return out;
}

async function fetchAllVideoResources(): Promise<VideoResourceRow[]> {
  const all: VideoResourceRow[] = [];
  const pageSize = 1000;
  let from = 0;

  while (true) {
    const { data, error } = await supabase
      .from("resources")
      .select("id,course_id,section_id,title,youtube_id,archive_url,video_url,ordering")
      .eq("resource_type", "video")
      .order("id", { ascending: true })
      .range(from, from + pageSize - 1);

    if (error) throw new Error(`Failed to fetch video resources: ${error.message}`);
    const rows = (data ?? []) as VideoResourceRow[];
    if (rows.length === 0) break;

    all.push(...rows);
    if (rows.length < pageSize) break;
    from += pageSize;
  }

  return all;
}

async function fetchSectionsByCourses(courseIds: number[]): Promise<Map<number, string>> {
  const sectionTitleById = new Map<number, string>();
  const batches = chunk(courseIds, 200);
  const pageSize = 1000;

  for (const ids of batches) {
    let from = 0;
    while (true) {
      const { data, error } = await supabase
        .from("course_sections")
        .select("id,course_id,title")
        .in("course_id", ids)
        .order("id", { ascending: true })
        .range(from, from + pageSize - 1);

      if (error) throw new Error(`Failed to fetch course sections: ${error.message}`);
      const rows = (data ?? []) as CourseSectionRow[];
      if (rows.length === 0) break;

      for (const row of rows) {
        sectionTitleById.set(row.id, row.title);
      }

      if (rows.length < pageSize) break;
      from += pageSize;
    }
  }

  return sectionTitleById;
}

async function fetchAllGenericSections(): Promise<Map<number, string>> {
  const byId = new Map<number, string>();
  const pageSize = 1000;
  let from = 0;

  while (true) {
    const { data, error } = await supabase
      .from("course_sections")
      .select("id,title")
      .or("title.eq.Download file,title.eq.Download video")
      .order("id", { ascending: true })
      .range(from, from + pageSize - 1);

    if (error) throw new Error(`Failed to fetch generic sections: ${error.message}`);
    const rows = (data ?? []) as Array<{ id: number; title: string }>;
    if (rows.length === 0) break;

    for (const row of rows) {
      byId.set(row.id, row.title);
    }

    if (rows.length < pageSize) break;
    from += pageSize;
  }

  return byId;
}

async function fetchResourcesBySectionIds(sectionIds: number[]): Promise<Map<string, SectionResourceRow[]>> {
  const bySection = new Map<string, SectionResourceRow[]>();
  const batches = chunk(sectionIds, 200);

  for (const ids of batches) {
    const { data, error } = await supabase
      .from("resources")
      .select("section_id,title,resource_type,ordering,archive_url,video_url,pdf_path")
      .in("section_id", ids)
      .order("ordering", { ascending: true });

    if (error) throw new Error(`Failed to fetch resources by section: ${error.message}`);

    for (const row of (data ?? []) as SectionResourceRow[]) {
      if (!row.section_id) continue;
      const key = String(row.section_id);
      if (!bySection.has(key)) bySection.set(key, []);
      bySection.get(key)!.push(row);
    }
  }

  return bySection;
}

async function mergeProgressAndDeleteDuplicates(
  canonicalId: number,
  duplicateIds: number[],
  dryRun: boolean,
): Promise<{ mergedUsers: number; deletedProgressRows: number; deletedResourceRows: number }> {
  if (duplicateIds.length === 0) {
    return { mergedUsers: 0, deletedProgressRows: 0, deletedResourceRows: 0 };
  }

  const allResourceIds = [canonicalId, ...duplicateIds];
  const { data: progressRows, error: progressError } = await supabase
    .from("user_video_progress")
    .select("id,user_id,resource_id,completed,completed_at,updated_at")
    .in("resource_id", allResourceIds);

  if (progressError) {
    throw new Error(`Failed to fetch video progress for dedupe: ${progressError.message}`);
  }

  const byUser = new Map<string, { completed: boolean; completedAt: string | null; updatedAt: string | null }>();
  for (const row of (progressRows ?? []) as UserVideoProgressRow[]) {
    const current = byUser.get(row.user_id) ?? {
      completed: false,
      completedAt: null,
      updatedAt: null,
    };

    current.completed = current.completed || Boolean(row.completed);
    if (row.completed_at && (!current.completedAt || row.completed_at > current.completedAt)) {
      current.completedAt = row.completed_at;
    }
    if (row.updated_at && (!current.updatedAt || row.updated_at > current.updatedAt)) {
      current.updatedAt = row.updated_at;
    }

    byUser.set(row.user_id, current);
  }

  const nowIso = new Date().toISOString();
  const mergedRows = Array.from(byUser.entries()).map(([userId, payload]) => ({
    user_id: userId,
    resource_id: canonicalId,
    completed: payload.completed,
    completed_at: payload.completedAt,
    updated_at: payload.updatedAt ?? nowIso,
  }));

  if (!dryRun && mergedRows.length > 0) {
    const { error: upsertError } = await supabase
      .from("user_video_progress")
      .upsert(mergedRows, { onConflict: "user_id,resource_id" });

    if (upsertError) {
      throw new Error(`Failed to merge user video progress: ${upsertError.message}`);
    }
  }

  let deletedProgressRows = 0;
  if (!dryRun) {
    const { data: deletedProgress, error: deleteProgressError } = await supabase
      .from("user_video_progress")
      .delete()
      .in("resource_id", duplicateIds)
      .select("id");

    if (deleteProgressError) {
      throw new Error(`Failed to delete duplicate user video progress rows: ${deleteProgressError.message}`);
    }
    deletedProgressRows = deletedProgress?.length ?? 0;
  }

  let deletedResourceRows = 0;
  if (!dryRun) {
    const { data: deletedResources, error: deleteResourceError } = await supabase
      .from("resources")
      .delete()
      .in("id", duplicateIds)
      .select("id");

    if (deleteResourceError) {
      throw new Error(`Failed to delete duplicate resources: ${deleteResourceError.message}`);
    }
    deletedResourceRows = deletedResources?.length ?? 0;
  }

  return {
    mergedUsers: mergedRows.length,
    deletedProgressRows,
    deletedResourceRows,
  };
}

async function main() {
  const options = parseCliOptions(process.argv.slice(2));
  console.log("=== Video Resource Cleanup ===");
  console.log(`dry-run=${options.dryRun}`);

  const videoResources = await fetchAllVideoResources();
  console.log(`Loaded ${videoResources.length} video resources`);

  const courseIds = Array.from(new Set(videoResources.map((row) => row.course_id)));
  const sectionTitleById = await fetchSectionsByCourses(courseIds);
  const genericSections = await fetchAllGenericSections();
  for (const [id, title] of genericSections) {
    sectionTitleById.set(id, title);
  }
  console.log(`Loaded section titles for ${sectionTitleById.size} sections`);

  const genericSectionIds = Array.from(sectionTitleById.entries())
    .filter(([, title]) => isGenericDownloadLabel(title) || isAutoGeneratedMediaTitle(title))
    .map(([id]) => id);
  const resourcesBySectionId = await fetchResourcesBySectionIds(genericSectionIds);

  const sectionFixes: { id: number; title: string }[] = [];
  for (const [sectionId, sectionTitle] of sectionTitleById) {
    if (!isGenericDownloadLabel(sectionTitle) && !isAutoGeneratedMediaTitle(sectionTitle)) continue;
    const sectionResources = resourcesBySectionId.get(String(sectionId)) ?? [];
    if (sectionResources.length === 0) continue;

    const sorted = [...sectionResources].sort((a, b) => {
      const priority = (type: string): number => {
        if (type === "video") return 0;
        if (type === "problem_set" || type === "exam" || type === "recitation") return 1;
        if (type === "lecture_notes") return 2;
        if (type === "solution") return 3;
        return 4;
      };
      const diff = priority(a.resource_type) - priority(b.resource_type);
      if (diff !== 0) return diff;
      return a.ordering - b.ordering;
    });

    let bestTitle = sorted.find((row) => isPreferredHumanTitle(row.title))?.title ?? null;
    if (!bestTitle) {
      for (const row of sorted) {
        if (row.resource_type === "video") {
          const derived = deriveTitleFromMediaUrl(row.archive_url ?? row.video_url ?? "");
          if (derived) {
            bestTitle = derived;
            break;
          }
        }
        if (row.pdf_path) {
          const derivedPdf = deriveTitleFromPdfPath(row.pdf_path);
          if (derivedPdf) {
            bestTitle = derivedPdf;
            break;
          }
        }
      }
    }

    if (!bestTitle) bestTitle = `Video Lesson ${sectionId}`;

    if (bestTitle !== sectionTitle) {
      sectionFixes.push({ id: sectionId, title: bestTitle });
    }
  }

  if (!options.dryRun) {
    for (const fix of sectionFixes) {
      const { error } = await supabase
        .from("course_sections")
        .update({ title: fix.title })
        .eq("id", fix.id);
      if (error) throw new Error(`Failed to update section ${fix.id}: ${error.message}`);
      sectionTitleById.set(fix.id, fix.title);
    }
  } else {
    for (const fix of sectionFixes) {
      sectionTitleById.set(fix.id, fix.title);
    }
  }
  console.log(`Section title fixes ${options.dryRun ? "planned" : "applied"}: ${sectionFixes.length}`);

  const titleFixes: { id: number; title: string }[] = [];
  for (const row of videoResources) {
    if (!isGenericDownloadLabel(row.title) && !isAutoGeneratedMediaTitle(row.title)) continue;

    const sectionTitle = row.section_id ? sectionTitleById.get(row.section_id) ?? null : null;
    let bestTitle = sectionTitle && isPreferredHumanTitle(sectionTitle) ? sectionTitle : null;

    if (!bestTitle && row.archive_url) {
      bestTitle = deriveTitleFromMediaUrl(row.archive_url);
    }
    if (!bestTitle && row.video_url) {
      bestTitle = deriveTitleFromMediaUrl(row.video_url);
    }
    if (!bestTitle) {
      bestTitle = `Video Lesson ${row.id}`;
    }

    if (bestTitle && bestTitle !== row.title) {
      titleFixes.push({ id: row.id, title: bestTitle });
    }
  }

  if (!options.dryRun) {
    for (const fix of titleFixes) {
      const { error } = await supabase
        .from("resources")
        .update({ title: fix.title })
        .eq("id", fix.id);
      if (error) throw new Error(`Failed to update resource ${fix.id}: ${error.message}`);
    }
  }
  console.log(`Title fixes ${options.dryRun ? "planned" : "applied"}: ${titleFixes.length}`);

  const refreshedResources = options.dryRun ? videoResources.map((row) => {
    const fix = titleFixes.find((f) => f.id === row.id);
    return fix ? { ...row, title: fix.title } : row;
  }) : await fetchAllVideoResources();

  const resourcesByCourse = new Map<number, VideoResourceRow[]>();
  for (const row of refreshedResources) {
    if (!resourcesByCourse.has(row.course_id)) resourcesByCourse.set(row.course_id, []);
    resourcesByCourse.get(row.course_id)!.push(row);
  }

  let duplicateGroups = 0;
  let duplicateRows = 0;
  let mergedUsers = 0;
  let deletedProgressRows = 0;
  let deletedResourceRows = 0;
  let deletedEmptySections = 0;
  let lastLoggedDuplicateMilestone = 0;

  for (const [courseId, rows] of resourcesByCourse) {
    const byKey = new Map<string, VideoResourceRow[]>();
    for (const row of rows) {
      const key = videoKey(row);
      if (!byKey.has(key)) byKey.set(key, []);
      byKey.get(key)!.push(row);
    }

    for (const keyRows of byKey.values()) {
      if (keyRows.length <= 1) continue;

      duplicateGroups++;
      duplicateRows += keyRows.length - 1;

      const canonical = chooseCanonical(keyRows);
      const duplicateIds = keyRows
        .map((row) => row.id)
        .filter((id) => id !== canonical.id);

      const titleCandidate = keyRows.find((row) => !isGenericDownloadLabel(row.title))?.title ?? null;
      if (titleCandidate && canonical.title !== titleCandidate && !options.dryRun) {
        const { error } = await supabase
          .from("resources")
          .update({ title: titleCandidate })
          .eq("id", canonical.id);
        if (error) throw new Error(`Failed to improve canonical title for resource ${canonical.id}: ${error.message}`);
      }

      const mergeResult = await mergeProgressAndDeleteDuplicates(
        canonical.id,
        duplicateIds,
        options.dryRun,
      );

      mergedUsers += mergeResult.mergedUsers;
      deletedProgressRows += mergeResult.deletedProgressRows;
      deletedResourceRows += mergeResult.deletedResourceRows;
    }

    if (duplicateGroups >= lastLoggedDuplicateMilestone + 50) {
      lastLoggedDuplicateMilestone = Math.floor(duplicateGroups / 50) * 50;
      console.log(`Processed duplicate groups so far: ${duplicateGroups} (course=${courseId})`);
    }
  }

  const emptyGenericSectionIds = Array.from(sectionTitleById.entries())
    .filter(([sectionId, title]) => isGenericDownloadLabel(title) && !resourcesBySectionId.has(String(sectionId)))
    .map(([sectionId]) => sectionId);

  if (!options.dryRun && emptyGenericSectionIds.length > 0) {
    for (const ids of chunk(emptyGenericSectionIds, 200)) {
      const { data, error } = await supabase
        .from("course_sections")
        .delete()
        .in("id", ids)
        .select("id");

      if (error) throw new Error(`Failed to delete empty generic sections: ${error.message}`);
      deletedEmptySections += data?.length ?? 0;
    }
  }

  console.log("\n=== Cleanup Summary ===");
  console.log(`courses_scanned=${resourcesByCourse.size}`);
  console.log(`section_title_fixes=${sectionFixes.length}`);
  console.log(`title_fixes=${titleFixes.length}`);
  console.log(`duplicate_groups=${duplicateGroups}`);
  console.log(`duplicate_rows=${duplicateRows}`);
  console.log(`merged_user_progress_users=${mergedUsers}`);
  console.log(`deleted_progress_rows=${deletedProgressRows}`);
  console.log(`deleted_resource_rows=${deletedResourceRows}`);
  console.log(`deleted_empty_generic_sections=${deletedEmptySections}`);
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
